services:
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=America/Caracas
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_USER=admin
      - MAILDEV_WEB_PASS=123456
      - MAILDEV_INCOMING_USER=admin
      - MAILDEV_INCOMING_PASS=123456
    ports:
      - "8080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
