version: "3"
services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - type: bind
        source: /home/ubuntu/sonarqube/data
        target: /opt/sonarqube/data
      - type: bind
        source: /home/ubuntu/sonarqube/extensions
        target: /opt/sonarqube/extensions
      - type: bind
        source: /home/ubuntu/sonarqube/logs
        target: /opt/sonarqube/logs
    ports:
      - "9000:9000"
  init:
      image: bash
      privileged: true
      user: root
      volumes:
        - ./init.sh:/mnt/init.sh 
      command: ["sh", "-e", "/mnt/init.sh"]
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - type: bind
        source: /home/ubuntu/sonarqube/conf
        target: /var/lib/postgresql
      - type: bind
        source: /home/ubuntu/sonarqube/pdata
        target: /var/lib/postgresql/data
