services:
  dockergc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- $DOCKERDIR/appdata/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude00
    environment:
      - CRON: 0 0 0 * *
      - FORCE_IMAGE_REMOVAL: 1
      - FORCE_CONTAINER_REMOVAL: 0
      - GRACE_PERIOD_SECONDS: 604800
      - DRY_RUN: 0
      - CLEAN_UP_VOLUMES: 1
      - TZ: $TZ
