version: '3'

services:
  mysql-pro:
    image: mysql:8.0.36
    container_name: mysql-pro
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    #ports:
    #  - 3306:3306
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    restart: on-failure
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - network-pro

  php-pro:
    container_name: php-pro
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/appdata/wwwroot
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 1m
    depends_on:
      - mysql-pro
    networks:
      - network-pro

  web-pro:
    image: nginx:1.25.4
    container_name: web-pro
    restart: on-failure
    ports:
      - 8081:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/appdata/wwwroot
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 5m
      timeout: 3s
      retries: 1
      start_period: 1m
    depends_on:
      - php-pro
      - mysql-pro
    networks:
      - network-pro

networks:
  network-pro:
    external: true
