services:
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - './unbound.conf:/etc/unbound/unbound.conf'
    restart: always

#networks:
#  ip6net:
#    enable_ipv6: true
#    ipam:
#      config:
#        - subnet: fd00::/8
